services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  postgres:
