version: '3.4'

services:
  app:
    build:
      context: .
      target: development
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm run dev

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  redis:
    image: redis

volumes:
  postgres:
